# Generated by Django 3.2 on 2023-06-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
    ]
